/* A- Création des tables */
CREATE TABLE PIECE( 
NOP NUMBER(3),
DESIGNATION CHAR(20),
COULEUR CHAR(15),
POIDS NUMBER(5,2) 
);
CREATE TABLE SERVICE(
NOS NUMBER(3),
INTITULE CHAR(20),
LOCALISATION CHAR(30) 
);
CREATE TABLE ORDRE( 
NOP NUMBER(3),
NOS NUMBER(3),
QUANTITE NUMBER(3) 
);
CREATE TABLE NOMENCLATURE(
NOPA NUMBER(3),
NOPC NUMBER(3),
QUANTITE NUMBER(3) 
);
INSERT INTO PIECE values(100,'COUTON','BLEU',10.6);
INSERT INTO PIECE values(101,'HARIR','JAUNE',17.76);
INSERT INTO PIECE values(102,'NOLOU','ROUGE',70.5);


INSERT INTO SERVICE values(10,'MASSIRA','TIZNIT');
INSERT INTO SERVICE values(11,'WAHDA','AGADIR');

INSERT INTO ORDRE values(101,10,10);
INSERT INTO ORDRE values(102,11,20);

INSERT INTO NOMENCLATURE values(150,170,50);
INSERT INTO NOMENCLATURE values(151,171,100);
/* B- Contraintes d’intégrité */
/* 1 */
INSERT INTO PIECE values(103,'P1','NOIR',10);
INSERT INTO PIECE values(103,'P2','ROUGE',17);
/* 2 */
INSERT INTO SERVICE values(12,'ARGANA','SAFI');
INSERT INTO SERVICE values(12,'NOUR','RABAT');
/* 3 */
INSERT INTO ORDRE values(50,70,10);
INSERT INTO ORDRE values(51,71,20);
/* 4 */
INSERT INTO NOMENCLATURE values(350,570,50);
INSERT INTO NOMENCLATURE values(351,571,100);
/* 5 */
ALTER TABLE PIECE 
ADD CONSTRAINT piece_pk PRIMARY KEY (NOP);

ALTER TABLE SERVICE 
ADD CONSTRAINT service_pk PRIMARY KEY (NOS);

ALTER TABLE ORDRE
ADD CONSTRAINT order_pk PRIMARY KEY (NOP, NOS);

ALTER TABLE ORDRE
ADD CONSTRAINT order_fk1 FOREIGN KEY (NOP) REFERENCES PIECE (NOP);

ALTER TABLE ORDRE
ADD CONSTRAINT order_fk2 FOREIGN KEY (NOS) REFERENCES SERVICE (NOS);

ALTER TABLE NOMENCLATURE
ADD CONSTRAINT nomenclature_pk PRIMARY KEY (NOPA, NOPC);

ALTER TABLE NOMENCLATURE
ADD CONSTRAINT nomenclature_fk1 FOREIGN KEY (NOPA) REFERENCES PIECE (NOP);

ALTER TABLE NOMENCLATURE
ADD CONSTRAINT nomenclature_fk2 FOREIGN KEY (NOPC) REFERENCES PIECE (NOP);
/* 6 */
DELETE FROM PIECE WHERE DESIGNATION IN ('P1','P2');
/* 7 */
ALTER TABLE PIECE 
ADD CONSTRAINT pience_ck CHECK (COULEUR in ('ROUGE','VERTE','BLEUE','JAUNE')); 

/* C- Modification de la structure de la base */
/* 1 */
ALTER TABLE PIECE MODIFY (DESIGNATION CHAR(30)) ;
ALTER TABLE SERVICE MODIFY (INTITULE CHAR(30)) ;
/* 2 */
ALTER TABLE SERVICE MODIFY (LOCALISATION CHAR(20)) ;
/* 3 */
ALTER TABLE SERVICE ADD (DIRECTEUR CHAR(20)) ;
/* 4 */
UPDATE SERVICE 
SET LOCALISATION = NULL;
/* 5 */
ALTER TABLE PIECE DROP PRIMARY KEY ;
/* 6 */
ALTER TABLE PIECE DROP CONSTRAINT pience_ck ;
/* 7 */
DROP TABLE NOMENCLATURE ;
/* 8 */
DROP TABLE ORDRE CASCADE CONSTRAINTS ;

